[book]
title = "SICP 여정"
description = "SICP 여정"
language = "ko"
src = "src"

[output.html]
no-section-label = true
site-url = "/sicp-journey/"
git-repository-url = "https://github.com/netpyoung/sicp-journey"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/netpyoung/sicp-journey/edit/main/{path}"

additional-css = ["theme/css/custom.css"]

## Ref: https://rust-lang.github.io/mdBook/format/mathjax.html
## mathjax-suport = true 하면 헤더에 js가 삽입이 되긴 하는데 2버전 코드가 삽입된다.
## <script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
##
## 3버전을 쓰고 싶다면, theme/head.hbs를 수정하자.
## ref:
##  - 기본: https://docs.mathjax.org/en/latest/basic/mathematics.html
##  - cdn
##    - https://cdnjs.com/libraries/mathjax
##    - https://www.jsdelivr.com/package/npm/mathjax
mathjax-support = true


[build]
extra-watch-dirs = ["../source/"]